// AUTO-GENERATED by trpcRoutesPlugin in vite.config.mts - DO NOT EDIT

import { trpcRouter as productsRouter } from "../products/products.trpc";
import { trpcRouter as productCategoriesRouter } from "../products/categories/productCategories.trpc";

export const routes = {
    products: productsRouter,
    productCategories: productCategoriesRouter,
};
