module.exports = {
    apps: [
        {
            name: "comet-blocks-api",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace @comet/blocks-api dev"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-blocks-api-codegen-block-meta",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace @comet/blocks-api generate-block-meta:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-api",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace @comet/cms-api dev"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-api-codegen-schema",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace @comet/cms-api generate-schema:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-api-codegen-block-meta",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace @comet/cms-api generate-block-meta:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-blocks-admin",
            script: ["npx wait-on -l tcp:$ADMIN_PORT", "npx yarn workspace @comet/blocks-admin start"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-blocks-admin-codegen-block-types",
            script: ["npx wait-on -l tcp:$ADMIN_PORT", "npx yarn workspace @comet/blocks-admin generate-block-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-admin",
            script: ["npx wait-on -l tcp:$ADMIN_PORT", "npx yarn workspace @comet/cms-admin start"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-admin-codegen-graphql-types",
            script: ["npx wait-on -l tcp:$ADMIN_PORT", "npx yarn workspace @comet/cms-admin generate-graphql-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-admin-codegen-block-types",
            script: ["npx wait-on -l tcp:$ADMIN_PORT", "npx yarn workspace @comet/cms-admin generate-block-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-site",
            script: ["npx wait-on -l tcp:$SITE_PORT", "npx yarn workspace @comet/cms-site dev"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-cms-site-codegen-block-types",
            script: ["npx wait-on -l tcp:$SITE_PORT", "npx yarn workspace @comet/cms-site generate-block-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-docker",
            script: "node docker-compose.js",
            namespace: "comet-cms",
            kill_timeout: 30000,
        },
        {
            name: "comet-demo-api",
            script: [
                "npx yarn workspace @comet/blocks-api build",
                "npx yarn workspace @comet/cms-api build",
                "npx wait-on -l tcp:$POSTGRESQL_PORT tcp:$IMGPROXY_PORT",
                "npx yarn workspace comet-demo-api db:migrate",
                "npx yarn workspace comet-demo-api  start:dev",
            ].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-admin",
            script: [
                "npx yarn workspace @comet/blocks-admin build",
                "npx yarn workspace @comet/cms-admin build",
                "npx wait-on -l tcp:$API_PORT",
                "npx yarn workspace comet-demo-admin start",
            ].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-admin-codegen",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace comet-demo-admin gql:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-admin-block-codegen",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace comet-demo-admin generate-block-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-site",
            script: ["npx yarn workspace @comet/cms-site build", "npx wait-on -l tcp:$API_PORT", "npx yarn workspace comet-demo-site dev"].join(
                " && ",
            ),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-site-codegen",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace comet-demo-site gql:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-site-block-codegen",
            script: ["npx wait-on -l tcp:$API_PORT", "npx yarn workspace comet-demo-site generate-block-types:watch"].join(" && "),
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-proxy",
            script: "node proxy.js",
            namespace: "comet-cms",
            autorestart: true,
        },
        {
            name: "comet-demo-idp",
            script: "node mock-idp.js",
            namespace: "comet-cms",
            autorestart: true,
        },
    ],
};
