/**
 * Generates the theme token files from a directory of design-token JSON files
 * (W3C DTCG format) exported by the "Design Token Exporter" Figma plugin.
 *
 * The directory holds a `manifest.json` that lists each collection, its modes,
 * and the token files per mode, alongside the `*.tokens.json` files themselves.
 * The output is one SCSS partial per token layer plus the generated prop-value
 * types, written to the sibling `theme/` directory. Re-run it whenever the
 * tokens change.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { format, resolveConfig } from "prettier";

const VARIABLE_PREFIX = "comet";
const CASCADE_LAYER = "comet";
const GENERATED_NOTICE = "Generated by the theme-token generator. Do not edit manually.";

interface DtcgToken {
    $type: string;
    $value: unknown;
}

interface TokenEntry {
    name: string;
    token: DtcgToken;
}

interface ModeFile {
    mode: string;
    tree: Record<string, unknown>;
}

type RenderStrategy =
    | { kind: "scope"; selector: string; mode?: string }
    | { kind: "attribute"; attribute: string }
    | { kind: "responsive"; baseMode: string; breakpointModes: Record<string, string> };

/**
 * `components` declare on the color-scheme scope rather than `:root`: a custom
 * property resolves its `var()` references against the element it is declared
 * on, and the semantic variables a component references are out of scope at
 * `:root`.
 *
 * A `scope` collection imports a single mode (`mode`, defaulting to `default`).
 * `brand` imports only its `dextinity` mode — the other brand modes in the
 * export belong to separate projects and are intentionally not imported.
 */
const COLLECTION_RENDER_STRATEGIES: Record<string, RenderStrategy> = {
    primitives: { kind: "scope", selector: ":root" },
    components: { kind: "scope", selector: "[data-comet-color-scheme]" },
    brand: { kind: "scope", selector: ":root", mode: "dextinity" },
    semantic: { kind: "attribute", attribute: "data-comet-color-scheme" },
    responsive: { kind: "responsive", baseMode: "mobile", breakpointModes: { desktop: "breakpoint-desktop" } },
};

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isToken(value: unknown): value is DtcgToken {
    return isRecord(value) && typeof value.$type === "string" && "$value" in value;
}

function isStringArray(value: unknown): value is string[] {
    return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function writeOut(message: string): void {
    process.stdout.write(`${message}\n`);
}

function fail(message: string): never {
    process.stderr.write(`${message}\n`);
    process.exit(1);
}

/**
 * The CSS custom-property name for a token. The name is already the kebab path;
 * characters invalid in a custom-property name (such as the decimal comma in
 * `space-0,5`) are replaced with `-`.
 */
function formatCssVariableName(name: string): string {
    return `--${VARIABLE_PREFIX}-${name.replace(/[^a-z0-9]+/gi, "-")}`;
}

function getReferencedTokenName(value: unknown): string | null {
    if (typeof value === "string" && value.startsWith("{") && value.endsWith("}")) {
        return value.slice(1, -1);
    }
    return null;
}

function colorChannel(channel: unknown): number {
    if (typeof channel !== "number") {
        throw new Error(`Expected a numeric color channel, got ${JSON.stringify(channel)}`);
    }
    return Math.round(channel * 255);
}

function formatColor(value: unknown): string {
    if (!isRecord(value) || !Array.isArray(value.components) || value.components.length < 3) {
        throw new Error(`Unsupported color value: ${JSON.stringify(value)}`);
    }
    const [red, green, blue] = value.components.map(colorChannel);
    const alpha = typeof value.alpha === "number" ? Math.round(value.alpha * 10000) / 10000 : 1;
    return alpha < 1 ? `rgb(${red} ${green} ${blue} / ${alpha})` : `rgb(${red} ${green} ${blue})`;
}

function formatDimension(value: unknown): string {
    if (!isRecord(value) || typeof value.value !== "number" || typeof value.unit !== "string") {
        throw new Error(`Unsupported dimension value: ${JSON.stringify(value)}`);
    }
    return `${value.value}${value.unit}`;
}

function formatString(value: unknown): string {
    if (typeof value !== "string") {
        throw new Error(`Expected a string, got ${JSON.stringify(value)}`);
    }
    return /\s/.test(value) ? `"${value}"` : value;
}

function formatLiteral(token: DtcgToken): string {
    switch (token.$type) {
        case "color":
            return formatColor(token.$value);
        case "dimension":
            return formatDimension(token.$value);
        case "fontWeight":
            if (typeof token.$value !== "number") {
                throw new Error(`Expected a numeric font weight, got ${JSON.stringify(token.$value)}`);
            }
            return String(token.$value);
        case "fontFamily":
        case "string":
            return formatString(token.$value);
        default:
            throw new Error(`Unsupported token type "${token.$type}"`);
    }
}

function renderDeclaration(entry: TokenEntry): string {
    const reference = getReferencedTokenName(entry.token.$value);
    const value = reference !== null ? `var(${formatCssVariableName(reference)})` : formatLiteral(entry.token);
    return `${formatCssVariableName(entry.name)}: ${value};`;
}

/** The token entries of a flat token file, skipping `$`-prefixed metadata. */
function getTokenEntries(tree: Record<string, unknown>): TokenEntry[] {
    const entries: TokenEntry[] = [];
    for (const [name, value] of Object.entries(tree)) {
        if (name.startsWith("$")) {
            continue;
        }
        if (isToken(value)) {
            entries.push({ name, token: value });
        }
    }
    return entries;
}

/**
 * The token group an entry belongs to: its name without the final value
 * segment. `line-height` is a single CSS property, so it counts as one value
 * rather than two segments, keeping `…-size` and `…-line-height` together.
 */
function getGroupKey(name: string): string {
    const segments = name.split("-");
    const endsWithLineHeight = segments.length > 2 && segments[segments.length - 2] === "line" && segments[segments.length - 1] === "height";
    return segments.slice(0, endsWithLineHeight ? -2 : -1).join("-");
}

/**
 * Renders the declarations grouped by `getGroupKey`, one blank line between groups.
 * Tokens of the same group are collected together even when the input interleaves
 * them, in the order each group first appears. Prettier handles indentation.
 */
function renderSelectorBlock(selector: string, entries: TokenEntry[]): string {
    const groups = new Map<string, TokenEntry[]>();
    for (const entry of entries) {
        const key = getGroupKey(entry.name);
        const existing = groups.get(key);
        if (existing) {
            existing.push(entry);
        } else {
            groups.set(key, [entry]);
        }
    }
    const blocks = Array.from(groups.values(), (group) => group.map(renderDeclaration).join("\n"));
    return `${selector} {\n${blocks.join("\n\n")}\n}`;
}

function renderPartialFile(blocks: string[]): string {
    return `/* ${GENERATED_NOTICE} */\n\n@layer ${CASCADE_LAYER} {\n${blocks.join("\n\n")}\n}\n`;
}

function readDimensionValue(tree: Record<string, unknown>, name: string): number {
    const token = tree[name];
    if (!isToken(token) || !isRecord(token.$value) || typeof token.$value.value !== "number") {
        throw new Error(`Token "${name}" is not a dimension`);
    }
    return token.$value.value;
}

function getModeFile(collection: string, modeFiles: ModeFile[], mode: string): ModeFile {
    const modeFile = modeFiles.find((file) => file.mode === mode);
    if (!modeFile) {
        throw new Error(`Mode "${mode}" of collection "${collection}" not found`);
    }
    return modeFile;
}

function renderScope(selector: string, collection: string, modeFiles: ModeFile[], mode = "default"): string {
    const modeFile = getModeFile(collection, modeFiles, mode);
    return renderPartialFile([renderSelectorBlock(selector, getTokenEntries(modeFile.tree))]);
}

function renderAttribute(attribute: string, modeFiles: ModeFile[]): string {
    const blocks = modeFiles
        .slice()
        .sort((a, b) => a.mode.localeCompare(b.mode))
        .map((file) => renderSelectorBlock(`[${attribute}="${file.mode}"]`, getTokenEntries(file.tree)));
    return renderPartialFile(blocks);
}

function renderResponsive(
    strategy: Extract<RenderStrategy, { kind: "responsive" }>,
    collection: string,
    modeFiles: ModeFile[],
    primitives: Record<string, unknown>,
): string {
    const baseFile = getModeFile(collection, modeFiles, strategy.baseMode);
    const blocks = [renderSelectorBlock(":root", getTokenEntries(baseFile.tree))];
    for (const file of modeFiles) {
        const breakpointToken = strategy.breakpointModes[file.mode];
        if (!breakpointToken) {
            continue;
        }
        const minWidth = readDimensionValue(primitives, breakpointToken);
        const rootBlock = renderSelectorBlock(":root", getTokenEntries(file.tree));
        blocks.push(`@media (min-width: ${minWidth}px) {\n${rootBlock}\n}`);
    }
    return renderPartialFile(blocks);
}

function renderTypes(modesByCollection: Map<string, ModeFile[]>): string {
    const colorSchemeUnion = (modesByCollection.get("semantic") ?? [])
        .map((file) => `"${file.mode}"`)
        .sort()
        .join(" | ");
    return [`// ${GENERATED_NOTICE}`, "", `export type ThemeColorScheme = ${colorSchemeUnion};`, ""].join("\n");
}

async function formatGenerated(content: string, filePath: string): Promise<string> {
    const options = (await resolveConfig(filePath)) ?? {};
    return format(content, { ...options, filepath: filePath });
}

function readJson(filePath: string): unknown {
    return JSON.parse(readFileSync(filePath, "utf8"));
}

function readTokenTree(filePath: string): Record<string, unknown> {
    const parsed = readJson(filePath);
    if (!isRecord(parsed)) {
        fail(`${filePath} is not a token object`);
    }
    return parsed;
}

/**
 * Reads the manifest's `collections` — each collection's modes and the token
 * files per mode. The `styles` section (composite typography and effect tokens)
 * is intentionally ignored; it is not consumed by the components yet.
 */
function readCollections(inputDir: string): Record<string, Record<string, string[]>> {
    const parsed = readJson(join(inputDir, "manifest.json"));
    if (!isRecord(parsed) || !isRecord(parsed.collections)) {
        fail("manifest.json is missing a collections object");
    }
    const collections: Record<string, Record<string, string[]>> = {};
    for (const [collection, definition] of Object.entries(parsed.collections)) {
        if (!isRecord(definition) || !isRecord(definition.modes)) {
            fail(`Collection "${collection}" in manifest.json is missing a modes object`);
        }
        const modes: Record<string, string[]> = {};
        for (const [mode, fileNames] of Object.entries(definition.modes)) {
            if (!isStringArray(fileNames)) {
                fail(`Mode "${mode}" of collection "${collection}" must list its token files`);
            }
            modes[mode] = fileNames;
        }
        collections[collection] = modes;
    }
    return collections;
}

async function main(): Promise<void> {
    const inputDir = process.argv[2];
    if (!inputDir) {
        fail("Usage: generate-future-ui-theme-tokens <input-directory>");
    }

    const collections = readCollections(inputDir);
    const modesByCollection = new Map<string, ModeFile[]>();
    for (const [collection, modes] of Object.entries(collections)) {
        const modeFiles: ModeFile[] = [];
        for (const [mode, fileNames] of Object.entries(modes)) {
            const tree: Record<string, unknown> = {};
            for (const fileName of fileNames) {
                Object.assign(tree, readTokenTree(join(inputDir, fileName)));
            }
            modeFiles.push({ mode, tree });
        }
        modesByCollection.set(collection, modeFiles);
    }

    const primitivesModeFiles = modesByCollection.get("primitives");
    if (!primitivesModeFiles) {
        fail("No primitives collection found in the manifest");
    }
    const primitives = getModeFile("primitives", primitivesModeFiles, "default").tree;

    const outputDir = join(import.meta.dirname, "..", "theme");
    for (const [collection, modeFiles] of modesByCollection) {
        const strategy = COLLECTION_RENDER_STRATEGIES[collection];
        if (!strategy) {
            process.stderr.write(`Skipping collection "${collection}" with no render strategy\n`);
            continue;
        }
        let contents: string;
        switch (strategy.kind) {
            case "scope":
                contents = renderScope(strategy.selector, collection, modeFiles, strategy.mode);
                break;
            case "attribute":
                contents = renderAttribute(strategy.attribute, modeFiles);
                break;
            case "responsive":
                contents = renderResponsive(strategy, collection, modeFiles, primitives);
                break;
        }
        const fileName = `_${collection}.scss`;
        const filePath = join(outputDir, fileName);
        writeFileSync(filePath, await formatGenerated(contents, filePath));
        writeOut(`Wrote ${fileName}`);
    }

    const typesPath = join(outputDir, "types.ts");
    writeFileSync(typesPath, await formatGenerated(renderTypes(modesByCollection), typesPath));
    writeOut("Wrote types.ts");
}

await main();
