export default [
    "API_URL",
    "ADMIN_URL",
    "IDP_URL",
    "IDP_CLIENT_ID",
    "DAM_UPLOADS_MAX_FILE_SIZE",
    "IMGPROXY_MAX_SRC_RESOLUTION",
    "SITES_CONFIG",
    "DAM_ALLOWED_IMAGE_ASPECT_RATIOS",
    "COMET_DEMO_API_URL",
    "DAM_ADDITIONAL_MIMETYPES",
] as const;
