export const environment = [
    "ADMIN_URL",
    "PREVIEW_URL",
    "PUBLIC_SITE_CONFIGS",
    "BUILD_DATE",
    "BUILD_NUMBER",
    "COMMIT_SHA",
    "MUI_LICENSE_KEY",
    "BREVO_CAMPAIGN_URL",
    "BREVO_ALLOW_ADDING_CONTACTS_WITHOUT_DOI",
];
