export enum CorePermission {
    builds = "builds",
    dam = "dam",
    pageTree = "pageTree",
    pageTreeDeleteNode = "pageTreeDeleteNode",
    cronJobs = "cronJobs",
    translation = "translation",
    userPermissions = "userPermissions",
    prelogin = "prelogin",
    impersonation = "impersonation",
    fileUploads = "fileUploads",
    dependencies = "dependencies",
    warnings = "warnings",
    sitePreview = "sitePreview",
    blockPreview = "blockPreview",
    fullTextSearch = "fullTextSearch",
}
