import { type Shadows } from "@mui/material/styles";

export const shadows: Shadows = [
    "none",
    "0 0 4px 0 rgba(0,0,0,0.08)",
    "0 0 8px 0 rgba(0,0,0,0.1)",
    "0 0 20px 0 rgba(0,0,0,0.1)",
    "0 0 40px 0 rgba(0,0,0,0.1)",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
];
