import { Shadows } from "@mui/material/styles/shadows";

export const shadows: Shadows = [
    "none",
    "0 0 8px 0 rgba(0,0,0,0.10)",
    "0 0 20px 0 rgba(0,0,0,0.10)",
    "none",
    "0 0 40px 0 rgba(0,0,0,0.10)",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
];
