import chalk from "chalk";
import { ESLint } from "eslint";
import { promises as fs } from "fs";
import * as path from "path";

export async function writeGenerated(filePath: string, contents: string): Promise<void> {
    const header = `// This file has been generated by comet admin-generator.
    // You may choose to use this file as scaffold by moving this file out of generated folder and removing this comment.
    `;
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    const eslint = new ESLint({
        cwd: process.cwd(),
        fix: true,
    });
    const lintResult = await eslint.lintText(header + contents, {
        filePath,
    });

    if (lintResult[0].errorCount > 0 || lintResult[0].fatalErrorCount > 0) {
        const errorMessage = lintResult[0].messages
            .map((message) => {
                return message.message;
            })
            .join(".");

        console.error(chalk.red(`Linting error in ${filePath}: \n${errorMessage}`));
    }

    const output = lintResult[0] && lintResult[0].output ? lintResult[0].output : lintResult[0].source;
    await fs.writeFile(filePath, output ?? contents);
    console.log(`generated ${filePath}`);
}
