import { TypographyClassKey } from "@material-ui/core";
import { StyleRules } from "@material-ui/styles/withStyles";

export const getMuiTypographyOverrides = (): StyleRules<Record<string, unknown>, TypographyClassKey> => ({
    root: {},
    h1: {},
    h2: {},
    h3: {},
    h4: {},
    h5: {},
    h6: {},
    subtitle1: {},
    subtitle2: {},
    body1: {},
    body2: {},
    caption: {},
    button: {},
    overline: {},
    srOnly: {},
    alignLeft: {},
    alignCenter: {},
    alignRight: {},
    alignJustify: {},
    noWrap: {},
    gutterBottom: {
        marginBottom: 20,
    },
    paragraph: {},
    colorInherit: {},
    colorPrimary: {},
    colorSecondary: {},
    colorTextPrimary: {},
    colorTextSecondary: {},
    colorError: {},
    displayInline: {},
    displayBlock: {},
});
