import { promises as fs } from "fs";
import * as path from "path";
import ts from "typescript";

export async function writeGeneratedFile(filePath: string, contents: string): Promise<void> {
    const header = `// This file has been generated by comet api-generator.
    // You may choose to use this file as scaffold by moving this file out of generated folder and removing this comment.
    `;
    await fs.mkdir(path.dirname(filePath), { recursive: true });

    const sourceFile = ts.createSourceFile(filePath, header + contents, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
    const printer = ts.createPrinter({
        newLine: ts.NewLineKind.LineFeed,
        removeComments: false,
    });
    const prettyCode = printer.printFile(sourceFile);

    await fs.writeFile(filePath, prettyCode);
    console.log(`generated ${filePath}`);
}
