name: Chromatic

on:
    pull_request:
        paths:
            - packages/admin/admin-generator/**
        branches:
            - main
            - next
    push:
        paths:
            - packages/admin/admin-generator/**
        branches:
            - main
            - next

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref || github.ref }}
                  fetch-depth: 0

            - uses: pnpm/action-setup@v4

            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - run: pnpm install --frozen-lockfile

            - name: Publish admin-generator to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ADMIN_GENERATOR }}
                  workingDir: packages/admin/admin-generator
