name: Lint

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
    push:
        branches:
            - main
            - next

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v6
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: "Library: Clone translations"
              uses: actions/checkout@v6
              with:
                  repository: vivid-planet/comet-lang
                  path: "demo/admin/lang/comet-lang"

            - name: "Demo Admin: Clone translations"
              uses: actions/checkout@v6
              with:
                  repository: vivid-planet/comet-demo-lang
                  path: "demo/admin/lang/comet-demo-lang"

            - name: "Demo Site: Clone translations"
              uses: actions/checkout@v6
              with:
                  repository: vivid-planet/comet-demo-lang
                  path: "demo/site/lang/comet-demo-lang"

            - name: "Demo Api: Clone translations"
              uses: actions/checkout@v6
              with:
                  repository: vivid-planet/comet-demo-lang
                  path: "demo/api/lang/comet-demo-lang"

            - uses: ./.github/actions/setup
              with:
                  build-packages: "true"

            - name: Lint
              run: |
                  pnpm run lint:ci
                  # check for duplicate ids of formatted messages
                  pnpm run intl:extract
                  # check if schema files are up to date
                  pnpm --filter '@comet/cms-api' run generate-block-meta
                  pnpm --filter '@comet/cms-api' run generate-schema
                  git diff --exit-code HEAD --
