name: "Test Report"
on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
jobs:
    test-report-unit:
        name: "Test Report (unit)"
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/test-reporter@v3
              with:
                  artifact: test-results-unit
                  name: Tests
                  path: "**/junit-*.xml"
                  reporter: jest-junit
    test-report-storybook:
        name: "Test Report (storybook)"
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/test-reporter@v3
              with:
                  artifact: test-results-storybook
                  name: Tests
                  path: "**/junit-*.xml"
                  reporter: jest-junit
